name: 'Build'

on:
  workflow_dispatch:
  push:
    tags-ignore: ['**']
    branches: ['**']
  release:
    types: ['released', 'prereleased']

jobs:
  build-native:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        full-python-version:
          - '3.7.17'
          - '3.8.20'
          - '3.9.20'
          - '3.10.15'
          - '3.11.10'
          - '3.12.7'
          - '3.13.0'
    name: Native Python (${{ matrix.full-python-version }})

    steps:
      - uses: actions/checkout@v4
      - id: cache-native-python
        uses: actions/cache@v4
        with:
          path: native-python-${{ matrix.full-python-version }}.tar.gz
          key: native-python-${{ runner.os }}-${{ matrix.full-python-version }}-${{ hashFiles('build-python-native.sh') }}
      - if: steps.cache-native-python.outputs.cache-hit != 'true'
        run: ./build-python-native.sh ${{ matrix.full-python-version }}
      - uses: actions/upload-artifact@v4
        with:
          name: native-python-${{ matrix.full-python-version }}
          path: native-python-${{ matrix.full-python-version }}.tar.gz

  build-cross:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tttapa/toolchains:${{ matrix.host-triple }}-gcc13-1.0.1
      options: --user root
    needs: build-native
    strategy:
      matrix:
        full-python-version:
          - '3.7.17'
          - '3.8.20'
          - '3.9.20'
          - '3.10.15'
          - '3.11.10'
          - '3.12.7'
          - '3.13.0'
        host-triple:
          - 'aarch64-rpi3-linux-gnu'
          - 'armv6-rpi-linux-gnueabihf'
          - 'armv7-neon-linux-gnueabihf'
          - 'armv8-rpi3-linux-gnueabihf'
          - 'x86_64-centos7-linux-gnu'
          - 'x86_64-bionic-linux-gnu'
    permissions:
      contents: write
    name: Cross Python (${{ matrix.full-python-version }}, ${{ matrix.host-triple }})

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: native-python-${{ matrix.full-python-version }}
      - run: tar xf native-python-${{ matrix.full-python-version }}.tar.gz
      - run: echo "$PWD/native-python-${{ matrix.full-python-version }}/usr/local/bin" >> $GITHUB_PATH
      - run: echo "/home/develop/opt/x-tools/${{ matrix.host-triple }}/bin" >> $GITHUB_PATH
      - id: cache-cross-python
        uses: actions/cache@v4
        with:
          path: python-dev-${{ matrix.full-python-version }}-${{ matrix.host-triple }}.tar.gz
          key: cross-python-${{ runner.os }}-${{ matrix.full-python-version }}-${{ matrix.host-triple }}-${{ hashFiles('build-python-native.sh','build-python-cross.sh','config.site') }}
      - if: steps.cache-cross-python.outputs.cache-hit != 'true'
        run: ./build-python-cross.sh ${{ matrix.full-python-version }} ${{ matrix.host-triple }}
      - uses: actions/upload-artifact@v4
        with:
          name: python-dev-${{ matrix.full-python-version }}-${{ matrix.host-triple }}
          path: python-dev-${{ matrix.full-python-version }}-${{ matrix.host-triple }}.tar.gz
      - name: Release
        uses: softprops/action-gh-release@17cd0d34deddf848fc0e7d9be5202c148c270a0a
        if: ${{ github.event.action == 'released' || github.event.action == 'prereleased' }}
        with:
          files: python-dev-${{ matrix.full-python-version }}-${{ matrix.host-triple }}.tar.gz

  package:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tttapa/toolchains:${{ matrix.host-triple }}-gcc13-1.0.1
      options: --user root
    needs: build-cross
    strategy:
      matrix:
        host-triple:
          - 'aarch64-rpi3-linux-gnu'
          - 'armv6-rpi-linux-gnueabihf'
          - 'armv7-neon-linux-gnueabihf'
          - 'armv8-rpi3-linux-gnueabihf'
          - 'x86_64-centos7-linux-gnu'
          - 'x86_64-bionic-linux-gnu'
    permissions:
      contents: write
    name: Package (${{ matrix.host-triple }})

    steps:
      - uses: actions/checkout@v4
      # Download and extract all compiled versions of Python
      - uses: actions/download-artifact@v4
        with:
            name: python-dev-3.7.17-${{ matrix.host-triple }}
      - run: set -ex; v=3.7.17; dest="/home/develop/python-dev/x-tools/${{ matrix.host-triple }}"; mkdir -p "$dest/python$v"; tar xf python-dev-$v-${{ matrix.host-triple }}.tar.gz -C "$dest/python$v" --strip-components=1; ln -s "python$v" "$dest/python${v%.*}"
      - uses: actions/download-artifact@v4
        with:
            name: python-dev-3.8.20-${{ matrix.host-triple }}
      - run: set -ex; v=3.8.20; dest="/home/develop/python-dev/x-tools/${{ matrix.host-triple }}"; mkdir -p "$dest/python$v"; tar xf python-dev-$v-${{ matrix.host-triple }}.tar.gz -C "$dest/python$v" --strip-components=1; ln -s "python$v" "$dest/python${v%.*}"
      - uses: actions/download-artifact@v4
        with:
            name: python-dev-3.9.20-${{ matrix.host-triple }}
      - run: set -ex; v=3.9.20; dest="/home/develop/python-dev/x-tools/${{ matrix.host-triple }}"; mkdir -p "$dest/python$v"; tar xf python-dev-$v-${{ matrix.host-triple }}.tar.gz -C "$dest/python$v" --strip-components=1; ln -s "python$v" "$dest/python${v%.*}"
      - uses: actions/download-artifact@v4
        with:
            name: python-dev-3.10.15-${{ matrix.host-triple }}
      - run: set -ex; v=3.10.15; dest="/home/develop/python-dev/x-tools/${{ matrix.host-triple }}"; mkdir -p "$dest/python$v"; tar xf python-dev-$v-${{ matrix.host-triple }}.tar.gz -C "$dest/python$v" --strip-components=1; ln -s "python$v" "$dest/python${v%.*}"
      - uses: actions/download-artifact@v4
        with:
            name: python-dev-3.11.10-${{ matrix.host-triple }}
      - run: set -ex; v=3.11.10; dest="/home/develop/python-dev/x-tools/${{ matrix.host-triple }}"; mkdir -p "$dest/python$v"; tar xf python-dev-$v-${{ matrix.host-triple }}.tar.gz -C "$dest/python$v" --strip-components=1; ln -s "python$v" "$dest/python${v%.*}"
      - uses: actions/download-artifact@v4
        with:
            name: python-dev-3.12.7-${{ matrix.host-triple }}
      - run: set -ex; v=3.12.7; dest="/home/develop/python-dev/x-tools/${{ matrix.host-triple }}"; mkdir -p "$dest/python$v"; tar xf python-dev-$v-${{ matrix.host-triple }}.tar.gz -C "$dest/python$v" --strip-components=1; ln -s "python$v" "$dest/python${v%.*}"
      - uses: actions/download-artifact@v4
        with:
            name: python-dev-3.13.0-${{ matrix.host-triple }}
      - run: set -ex; v=3.13.0; dest="/home/develop/python-dev/x-tools/${{ matrix.host-triple }}"; mkdir -p "$dest/python$v"; tar xf python-dev-$v-${{ matrix.host-triple }}.tar.gz -C "$dest/python$v" --strip-components=1; ln -s "python$v" "$dest/python${v%.*}"
      - run: set -ex; dest="/home/develop/python-dev/x-tools/${{ matrix.host-triple }}"; ln -s "python3.12" "$dest/python3"; ln -s "python3" "$dest/python"
      # Download and prepare PyPy
      - run: |
          set -ex
          dest="/home/develop/python-dev/x-tools/${{ matrix.host-triple }}"
          mkdir -p "$dest"
          cd "$dest"
          for v in 3.10-v7.3.17 3.9-v7.3.16 3.8-v7.3.11 3.7-v7.3.9; do
            "$GITHUB_WORKSPACE/download-pypy.sh" $v ${{ matrix.host-triple }}
          done
      # Generate toolchain files and py-build-cmake config
      - uses: actions/download-artifact@v4
        with:
          name: native-python-3.12.7
      - run: tar xf native-python-3.12.7.tar.gz
      - run: echo "$PWD/native-python-3.12.7/usr/local/bin" >> $GITHUB_PATH
      - run: python3.12 gen-py-build-cmake-cross-config.py ${{ matrix.host-triple }} /home/develop/python-dev/x-tools
      - run: |
          chown -R 1000:1000 /home/develop/python-dev/x-tools
          chmod -R a-w /home/develop/python-dev/x-tools/${{ matrix.host-triple }}
      # Export python-dev
      - run: tar cJf python-dev-${{ matrix.host-triple }}.tar.xz -C /home/develop/python-dev x-tools
      - uses: actions/upload-artifact@v4
        with:
          name: python-dev-${{ matrix.host-triple }}
          path: python-dev-${{ matrix.host-triple }}.tar.xz
      - name: Release python-dev
        uses: softprops/action-gh-release@17cd0d34deddf848fc0e7d9be5202c148c270a0a
        if: ${{ github.event.action == 'released' || github.event.action == 'prereleased' }}
        with:
          files: python-dev-${{ matrix.host-triple }}.tar.xz
      # Export toolchain + python-dev
      - run: |
          chmod u+w /home/develop/opt/x-tools
          cp -a /home/develop/python-dev/x-tools /home/develop/opt
          chmod -R a-w /home/develop/opt/x-tools/${{ matrix.host-triple }}
      - run: tar cJf python-dev-${{ matrix.host-triple }}-with-toolchain.tar.xz -C /home/develop/opt x-tools
      - uses: actions/upload-artifact@v4
        with:
          name: python-dev-${{ matrix.host-triple }}-with-toolchain
          path: python-dev-${{ matrix.host-triple }}-with-toolchain.tar.xz
      - name: Release x-tools-python
        uses: softprops/action-gh-release@17cd0d34deddf848fc0e7d9be5202c148c270a0a
        if: ${{ github.event.action == 'released' || github.event.action == 'prereleased' }}
        with:
          files: python-dev-${{ matrix.host-triple }}-with-toolchain.tar.xz
